# Generated by Django 6.0.3 on 2026-04-07 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0006_alter_incident_status'),
        ('resources', '0002_inventory_consumption'),
        ('responders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alloca_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('active_hours', models.FloatField(default=0.0)),
                ('reso_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_stats', to='resources.resource')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_record', to='resources.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponderPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incid_handl', models.PositiveIntegerField(default=0)),
                ('avg_peak_load', models.FloatField(default=0.0)),
                ('succ_exec', models.PositiveIntegerField(default=0)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='responders.responder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disp_time_sec', models.PositiveIntegerField(default=0)),
                ('total_reso_time', models.PositiveIntegerField(default=0)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_record', to='incidents.incident')),
                ('primary_auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
