# Generated by Django 6.0.3 on 2026-04-07 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('incidents', '0006_alter_incident_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseMetrics',
            new_name='ResponseRecord',
        ),
    ]
