# Generated by Django 6.0.3 on 2026-04-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0004_alter_allocationdecision_unique_together'),
        ('resources', '0002_inventory_consumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=70, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_load', models.PositiveIntegerField(default=3)),
                ('skills', models.ManyToManyField(blank=True, related_name='responders', to='responders.capability')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load_count', models.PositiveIntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='incidents.incident')),
                ('units_assigned', models.ManyToManyField(blank=True, related_name='responders_assigned', to='resources.unit')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='responders.responder')),
            ],
            options={
                'unique_together': {('responder', 'incident')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='responders.responder')),
            ],
            options={
                'unique_together': {('responder', 'start_time', 'end_time')},
            },
        ),
    ]
