# Generated by Django 6.0.3 on 2026-04-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='control',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('responder', 'Responder'), ('admin', 'Admin'), ('authority', 'Authority')], default='citizen', max_length=50),
        ),
    ]
