# Generated by Django 6.0.3 on 2026-04-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_allocationdecision'),
        ('resources', '0002_inventory_consumption'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allocationdecision',
            unique_together={('unit', 'incident')},
        ),
    ]
