# Generated by Django 6.0.3 on 2026-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_allocationdecision_unique_together'),
        ('responders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_responders',
            field=models.ManyToManyField(blank=True, related_name='incidents_assigned', through='responders.Load', to='responders.responder'),
        ),
    ]
