# Generated by Django 6.0.3 on 2026-04-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_assigned_responders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=55),
        ),
    ]
